/* eslint-disable @next/next/no-page-custom-font */
import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Box } from '@mui/material'
import Main from '../src/containers/Main'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beauty Salon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"                                                            />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet"/>
      </Head>
      <Main/>  
    </div>
  )
}

export default Home